[package]
name = "javcap"
version = "0.1.0"
edition = "2021"

[dependencies]
app.workspace = true
config.workspace = true
video.workspace = true
nfo.workspace = true
spider.workspace = true

tokio.workspace = true
anyhow.workspace = true
validator.workspace = true
