[package]
name = "javcap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error.workspace = true
config.workspace = true
tokio.workspace = true
indicatif.workspace = true
console.workspace = true
walkdir.workspace = true
backend.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
time.workspace = true
