[workspace]
resolver = "2"
members = ["crates/app", "crates/config", "crates/javcap"]

[workspace.dependencies]
config = { path = "crates/config" }
app = { path = "crates/app" }

anyhow = "1.0.95"
tokio = { version = "1.43.0", features = [
    "macros",
    "rt-multi-thread",
    "fs",
    "io-util",
] }
whoami = "1.5.2"
toml = "0.8.19"
serde = { version = "1.0.217", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
