[workspace]
resolver = "2"
members = ["backend", "config", "javcap"]
default-members = ["javcap"]

[workspace.dependencies]
config = { path = "config" }
backend = { path = "backend" }

toml = "0.8.12"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
indicatif = { version = "0.17.8", features = ["tokio"] }
console = "0.15.8"
walkdir = "2.5.0"
nom = "7.1.3"
reqwest = { version = "0.12.3", features = [
    "json",
    "brotli",
    "deflate",
    "gzip",
    "rustls-tls",
], default-features = false }
scraper = "0.19.0"
async-trait = "0.1.80"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["time", "local-time"] }
time = { version = "0.3.36", features = ["macros"] }
indoc = "2.0.5"
base64 = "0.22.0"
anyhow = "1.0.82"
validator = { version = "0.18.1", features = ["derive"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
