[workspace]
resolver = "2"
members = [
    "crates/backend",
    "crates/config",
    "crates/error",
    "crates/javcap",
    "crates/video",
]

[workspace.dependencies]
error = { path = "crates/error" }
config = { path = "crates/config" }
video = { path = "crates/video" }
backend = { path = "crates/backend" }

toml = "0.8.12"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
thiserror = "1.0.58"
indicatif = { version = "0.17.8", features = ["tokio"] }
console = "0.15.8"
walkdir = "2.5.0"
nom = "7.1.3"
reqwest = { version = "0.12.3", features = [
    "json",
    "brotli",
    "deflate",
    "gzip",
] }
scraper = "0.19.0"
async-trait = "0.1.80"
tera = "1.19.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-appender = "0.2.3"
