task_limit = 3

# [[translators]]
# type = "youdao"
# key = ""
# secret = ""

[input]
path = ""
exts = ["mp4", "avi", "mov", "m4v", "mkv", "flv", "rmvb", "wmv"]
excludes = ["output"]

[output]
path = ""
rule = ["id", "name"]

[network]
timeout = 5
# proxy = ""

[url]
# avsox = ""
