[app]
quit_on_finish = false

[file]
root = "."
remove_empty = true
output = "output"
other = "other"
exclude = []
ext = ["mp4", "mkv", "avi", "ts"]

[network]
proxy = "http://127.0.0.1:8888"
timeout = 10
