[package]
name = "http-client"
version = "0.1.0"
edition = "2024"

[dependencies]
app.workspace = true

reqwest.workspace = true
bon.workspace = true
anyhow.workspace = true
ratelimit.workspace = true
tokio.workspace = true
