[package]
name = "nfo"
version = "0.1.0"
edition = "2024"

[dependencies]
bon.workspace = true
educe.workspace = true
fast2s.workspace = true
getset.workspace = true
indoc.workspace = true
quick-xml.workspace = true
validator.workspace = true
video.workspace = true

