[app]
# 是否应该在运行结束时退出。
quit_on_finish = false

[file]
# 运行的根目录，支持绝对路径和相对路径。
root = "."
# 视频的输出位置。
output = "output"
# 未能识别id的视频的输出位置。
other = "other"
# 不希望被扫描的文件夹名称，output和other参数对应的目录会被自动忽略。
exclude = []
# 那些后缀的文件会被识别为视频文件。
ext = ["mp4", "mkv", "avi", "ts", "mov"]
# 是否移除空目录,如果目录下只有.开头的文件或文件夹也会被认为是空目录。
remove_empty = false

[video]
# 是否翻译视频信息。
# 如果翻译失败会使用未翻译的信息。
# 可选择项
# disable
# app_world 一个免费的接口
translate = "disable"
# 视频该以哪种规则分类，默认为 厂商/号码，可选择的值为["title", "id", "director", "studio", "actor"]
rules = ["studio", "id"]

[network]
# 网络的代理地址。
proxy = "http://127.0.0.1:8888"
# 网络请求的超时时间。
timeout = 10

[avatar]
# 是否刷新emby中的头像。
refresh = false
# emby的访问地址。
host = "http://localhost:8096"
# emby的api key。
api_key = ""
