[package]
name = "video"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bon.workspace = true
getset.workspace = true
log.workspace = true
nom.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
test-case.workspace = true
