name: "ci"

on:
  pull_request:
    types:
      - opened

jobs:
  run-test:
    name: run-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Check spelling
        uses: crate-ci/typos@master

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install audit
        run: |
          cargo install cargo-audit

      - name: Run test
        run: |
          cargo audit
          cargo test --workspace --all-features --color always
