name: ci

on:
  pull_request:
    types:
      - opened

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Check spelling
        uses: crate-ci/typos@master

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install audit
        run: |
          cargo install cargo-audit

      - name: Run check
        run: |
          cargo audit
