name: ci

on:
  pull_request:
    types:
      - opened
  schedule:
    - cron: "0 22 * * *"

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@master

      - name: Check spelling
        uses: crate-ci/typos@master

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Install audit
        run: |
          cargo install cargo-audit

      - name: Run check
        run: |
          cargo audit

      - name: Run test
        run: |
          cargo test --workspace --all-features --color always
